#!/bin/bash
set_dir () { DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; }; set_dir
safe_source () { source $1; set_dir; }
safe_source $DIR/common.sh

echo_yellow "Needs re-test"
proxy_port=$1
[[ $proxy_port ]] || proxy_port=$NODE_PROXY_PORT

echo "Creating tunnel from $PROXY_ADDR:$NODE_PROXY_PORT to localhost:$proxy_port"
$SSH target_proxy -L $proxy_port:localhost:$NODE_PROXY_PORT
if is_sshd_heartbeating localhost $proxy_port; then
    echo_green "Connect target machine via localhost:$proxy_port"
else
    echo_yellow "Something went wrong!"
    exit 255
fi
