#!/bin/bash
set_dir () { DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; }
safe_source () { source $1; set_dir; }
set_dir
safe_source $DIR/common.sh

# Generate project specific SSH config file
# see https://superuser.com/q/1253960/187576 for older SSH clients
cat > $SSH_CONFIG <<EOF
Host *
    UserKnownHostsFile $known_hosts_file
    IdentityFile $KEY_FILE

Host target_direct
    Hostname $NODE_IP
    Port $NODE_PORT
    User $NODE_USER
EOF

if [[ ! -z $PROXY_ADDR ]]; then
    cat >> $SSH_CONFIG <<EOF

Host proxy
    Hostname    $PROXY_HOST
    Port        $PROXY_PORT
    User        $PROXY_USER

Host target_proxy
    Hostname localhost
    Port $NODE_PROXY_PORT
    User $NODE_USER
    ProxyJump proxy
EOF
fi

chown $USER_NAME $SSH_CONFIG
