#!/bin/bash
set_dir () { DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; }; set_dir
safe_source () { source $1; set_dir; }
safe_source $DIR/common.sh

#$DIR/create-tunnel
tmp=$(mktemp)

arg=$SSH_SOCKET_FILE
beforeat=${arg%@*}
afterat=${arg#*@}

# Workaround for linkup_normal creation which is a workaround for linkup
servername=${afterat%:*}
port=${afterat#*:}
port=${port%.*}
user=${beforeat#*-}

cat > $tmp <<EOF
Host linkup_normal  # <- this is a workaround for now
    Hostname    $servername
    Port        $port
    User        $user

Host linkup     # <- we actually prefer this one, but connection is broken for large files
    ControlMaster auto
    ControlPath $SSH_SOCKET_FILE

Host target
    Hostname localhost
    Port $NODE_RENDEZVOUS_PORT
    User $NODE_USER
    ProxyJump linkup_normal
EOF

echo_yellow "FIXME: Parsing proxy file name: $SSH_SOCKET_FILE"

$SSHFS -F $tmp target:/ $MOUNT_DIR
rm $tmp

# Create a symbolic link to actual mount dir
rm $NODE_MOUNT_LINK 2> /dev/null
ln -sf $MOUNT_DIR $NODE_MOUNT_LINK

