#!/bin/bash
set_dir () { DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; }; set_dir
safe_source () { source $1; set_dir; }
safe_source $DIR/common.sh

$DIR/create-ssh-config
$SSHFS target_proxy:/ $MOUNT_DIR

# Create a symbolic link to actual mount dir
rm $NODE_MOUNT_LINK 2> /dev/null
ln -sf $MOUNT_DIR $NODE_MOUNT_LINK
