#!/bin/bash
set_dir () { DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; }
safe_source () { source $1; set_dir; }
set_dir
safe_source $DIR/common.sh
params="$@"

$DIR/create-tunnel
$SSH $NODE_USER@localhost -p $NODE_RENDEZVOUS_PORT -i $KEY_FILE $params
