#!/bin/bash

set_dir () { DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; }
safe_source () { source $1; set_dir; }
set_dir

safe_source $DIR/common.sh
ssh_run_via_socket -L $NODE_RENDEZVOUS_PORT:localhost:$NODE_RENDEZVOUS_PORT
$DIR/backup-over-ssh.sh --source $NODE_USER@localhost:$NODE_RENDEZVOUS_PORT/ --backup $DIR/../snapshots/curr 
