#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
CONFIG="$DIR/../config.sh"

ln -sf "./$(basename $DIR)/Makefile" "$DIR/../Makefile"

if [[ ! -e "$CONFIG" ]]; then
  cp "$DIR/config-template.sh" "$CONFIG"
  nano "$CONFIG"
else
  echo "There is a configuration file already"
fi

touch "$DIR/../up-to-date"
