#!/bin/bash
set_dir () { DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; }
safe_source () { source $1; set_dir; }
set_dir

safe_source $DIR/common.sh
$DIR/create-ssh-config

params="$@"
if [[ $params ]]; then
    echo_yellow "params: $params"
fi

echo_green "Using proxy server: $PROXY_ADDR"
$SSH target_proxy $params
