#!/bin/bash
set_dir () { DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; }
safe_source () { source $1; set_dir; }
set_dir
safe_source $DIR/common.sh

#$DIR/create-tunnel
params="$@"
if [[ $params ]]; then
    echo_yellow "params: $params"
fi

tmp=$(mktemp)

cat > $tmp <<EOF
Host hello
ControlMaster auto
ControlPath $SSH_SOCKET_FILE
EOF

echo_green "Using proxy file: $SSH_SOCKET_FILE"
$SSH -F $tmp -J hello $NODE_USER@localhost -p $NODE_RENDEZVOUS_PORT -i $KEY_FILE $params

rm $tmp
