#!/bin/bash

set_dir () { DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; }
safe_source () { source $1; set_dir; }
set_dir

safe_source $DIR/common.sh

params="$@"
echo_green "Using direct connection: $NODE_IP:$NODE_PORT"
if [[ $params ]]; then
    echo_yellow "params: $params"
fi
$SSH target_direct $params
