#!/bin/bash
set_dir () { DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; }
safe_source () { source $1; set_dir; }
set_dir

safe_source $DIR/common.sh
$DIR/create-tunnel

$DIR/backup-over-ssh.sh --source $NODE_USER@localhost:$NODE_RENDEZVOUS_PORT/ --backup $DIR/../sync-root
